domain_path: D:\Vivado\Vitis\Projects\CPU_UART\export\CPU_UART\sw\standalone_microblaze_0
app_src_dir: D:\Vivado\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
